name: PonyParkour
version: '1.0'
main: fun.eqad.ponyparkour.PonyParkour
api-version: '1.20'
author: EQAD Network
libraries:
  - com.google.code.gson:gson:2.10.1
softdepend: [PlaceholderAPI]
commands:
  parkour:
    description: Main command for PonyParkour
    usage: /parkour <subcommand>
    aliases: [pk]
